name: aptible

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      APTIBLE_USERNAME:
        description: 'Heroku App name'
        required: true
      APTIBLE_PASSWORD:
        description: 'Heroku API key'
        required: true
      BOT_TOKEN:
        description: 'Telegram bot token'
        required: true
      OWNER_ID:
        description: "Owner's telegram ID"
        required: true
      DATABASE_URL:
        description: 'Database URL from MongoDB'
        required: true
      TELEGRAM_API:
        description: 'Telegram API ID from https://my.telegram.org/'
        required: true
      TELEGRAM_HASH:
        description: 'Telegram HASH from https://my.telegram.org/'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@v4
      with:
        type: git
        app: silent-ghost
        environment: unknown00
        username: ${{ inputs.APTIBLE_USERNAME }}
        password: ${{ inputs.APTIBLE_PASSWORD }}
